{{- if .Values.spec.gitops.applications.platformRbac.isEnabled | default false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-rbac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.gitops.applications.platformRbac.namespace | default "argo" }}
  project: {{ .Values.spec.gitops.applications.platformRbac.project | default "platform-system" }}
  source:
    path: {{ .Values.spec.gitops.applications.platformRbac.appPath }}
    repoURL: {{ .Values.spec.gitops.applications.platformRbac.repoURL | default .Values.spec.default.repoURL }}
    targetRevision: {{ .Values.spec.gitops.applications.platformRbac.targetRevision | default .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
        {{- range $val := .Values.spec.default.helm.valueFiles }}
          - {{ $val }}
        {{- end }}
{{- if .Values.spec.gitops.applications.platformRbac.isEnabledAutoSync | default false }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
{{- end }}
{{- end }}
