apiVersion: v2
name: thanos-sidecar
description: Thanos — long-term metrics storage (Store Gateway, Query, Compactor)
type: application
version: 0.1.0
appVersion: "0.39.2"

dependencies:
  - name: thanos
    version: "0.2.0"
    repository: https://thanos-community.github.io/helm-charts
