apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: default
  namespace: argo-events
spec:
  nats:
    native:
      # Single-node NATS — dev environment, HA not required
      replicas: 1
      auth: token
